version: '3.8'

services:
  registry:
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS_AND_PORT=localhost:8080

  node:
    build:
      context: .
      dockerfile: DockerfileNode
    environment:
      - SERVER_ADDRESS_AND_PORT=registry:8080
    depends_on:
      - registry
    deploy:
      mode: replicated
      replicas: 4